### ISSUE TITLE
Reorganise in directory structure and add new operator conventions such as domain_geometry

### ISSUE THREAD

**Issue by jakobsj** [vais-ral/CCPi-astra#17]

**Comment by paskino** [comment]
- [ ] remove `create_image_data` and `size` from `AstraProjectorMC` 
- [ ] remove `create_image_data`, `size` and `get_max_sing_val` in `AstraProjector3DSimple` 
- [ ] add `domain_geometry` `range_geometry` in `AstraProjector3DSimple` 
- [ ] create subdirectory `operators` and split the AstraProjectors there
- [ ] create subdirectory `processors` and put the `processors.py` there, as in https://github.com/vais-ral/CCPi-Framework/issues/265

closes #11
