### ISSUE TITLE
Operator norm (Speed)

### ISSUE THREAD

**Issue by epapoutsellis** [vais-ral/CCPi-astra#24]
https://github.com/vais-ral/CCPi-astra/blob/7ab438acd11d80580661c7416c6be104c47f0499/Wrappers/Python/ccpi/astra/operators/AstraProjectorMC.py#L68

The operator norm should be computed on one channel only. An easy (hack) solution atm would be

# Compute operator Norm
igtmp = ImageGeometry(voxel_num_x = N, voxel_num_y = N)
agtmp = AcquisitionGeometry('parallel','2D', angles, detectors) # No channels
Atmp = AstraProjectorSimple(igtmp, agtmp, dev)

and then use power method.

**Comment by paskino** [comment]
BTW, the `norm` should be calculated by method `calculate_norm` rather than `norm`.

**Comment by epapoutsellis** [comment]
Closed #33
