### ISSUE TITLE
define the DEFAULT_ASTRA_ACQUISITION_DATA_DIMENSION_LABELS and DEFAULT_ASTRA_IMAGE_DATA_DIMENSION_LABELS

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-astra#34]
define the `DEFAULT_ASTRA_ACQUISITION_DATA_DIMENSION_LABELS` and `DEFAULT_ASTRA_IMAGE_DATA_DIMENSION_LABELS` as package variables (well, constant!) so that it is impossible to get wrong.

```python

ig = ImageGeometry(voxel_num_x = 256, voxel_num_y = 256, voxel_num_z = 256, \
            channels = 80, \
            dimension_labels=ccpi.astra.DEFAULT_ASTRA_IMAGE_DATA_DIMENSION_LABELS)
```

See https://github.com/vais-ral/CCPi-Framework/pull/363

**Comment by gfardell** [comment]
This is closed by #89 and uses the DataOrder class in framework
