### ISSUE TITLE
Processors allocate memory for output and then discard it

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-astra#35]
In `AstraForwardProjector3D.py` and `AstraBackwardProjector3D.py` we create the output array and then delete it at the following lines:

https://github.com/vais-ral/CCPi-astra/blob/master/Wrappers/Python/ccpi/astra/processors/AstraForwardProjector3D.py#L64

https://github.com/vais-ral/CCPi-astra/blob/master/Wrappers/Python/ccpi/astra/processors/AstraBackProjector3D.py#L60

Same happens for the other processors, except possibly the Multi-Channel one.

**Comment by epapoutsellis** [comment]
We have to delete the id. We do not delete the array. Same for the MC processor [here](https://github.com/vais-ral/CCPi-astra/blob/master/Wrappers/Python/ccpi/astra/processors/AstraForwardProjectorMC.py#L33)

Suggest to close this issue.
