### ISSUE TITLE
ImageGeometry for Astra

### ISSUE THREAD

**Issue by epapoutsellis** [vais-ral/CCPi-astra#37]
Why do we have get_min, etc for the ['image geometry'](https://github.com/vais-ral/CCPi-astra/blob/master/Wrappers/Python/ccpi/astra/utils/convert_geometry_to_astra.py#L9)

**Comment by gfardell** [comment]
This is the reconstruction volume. You specify the number of voxels, the voxel size and the centre of the volume, and get_min() and get_max() then give the position of the edges these define, which is what astra needs to create the volume geometry.
