### ISSUE TITLE
voxel scaling 

### ISSUE THREAD

**Issue by epapoutsellis** [vais-ral/CCPi-astra#39]
Why do we have

https://github.com/vais-ral/CCPi-astra/blob/master/Wrappers/Python/ccpi/astra/processors/AstraBackProjector.py#L78

**Comment by jakobsj** [comment]
This is required to make up for inconsistencies in ASTRA up until v 1.8.
These were fixed in 1.9.0dev so when we change to use that, we need to
remove these scalings.

**Comment by epapoutsellis** [comment]
but with this scaling backprojection will be off the initial range of the phantom i.e., [0,1]

**Comment by jakobsj** [comment]
I think it is correct and was worked out for each geometry individually so
that a reconstruction (not necessarily a backprojection alone) will have
values in the correct range.  Try the dot test.

**Comment by epapoutsellis** [comment]
Scaling for FBP and FP & BP are ok in the #33  using astra 1.8.  As a next step, we should use astra dev 1.9.
