### ISSUE TITLE
Parallel Geometry voxel_size == detector_voxel_size

### ISSUE THREAD

**Issue by epapoutsellis** [vais-ral/CCPi-astra#40]
In parallel geometry, if we setup the image geometry then 
acqusition_geometry should have as  detector_pixel_size  the voxel_size

**Comment by jakobsj** [comment]
I am not sure I understand. Is this the "default" choice of voxel size we discussed the other day, so that given an acquisition geometry loaded in with some data, then the imagegeometry voxel size should be specified automatically from there?

**Comment by epapoutsellis** [comment]
Let's say we have sth like 
``` python
    ig = ImageGeometry(voxel_num_x = N, voxel_num_y = N,
                       voxel_size_x = voxels, voxel_size_y = voxels)
    data = ImageData(phantom_2D)
    
    detectors =  N
    angles = np.linspace(0, np.pi, 180, dtype=np.float32)
    
    ag = AcquisitionGeometry('parallel','2D', angles, 
                             detectors,
                             pixel_size_h = voxels)

```
then everything is fine. But, if the user forgers pixels_size_h, then by default will be 1 and give wrong output. Meaning that if it is parallel pixel size should be by default equal to voxel_size_x.

```  python 
    ag = AcquisitionGeometry('parallel','2D', angles, 
                             detectors)

```

**Comment by jakobsj** [comment]
I agree we should have a discussion about default values.  What you are
suggesting sounds a bit...  reversed, to me though - I would say that from
reading in data, we should be provided with the AcquisitionGeometry.  Then
the user needs to set the ImageGeometry. In doing that, it might make sense
to set voxel_size_x etc to ag.pixel_size_h.

**Comment by evelinaametova** [comment]
we can implement a new method for AcquisitionGeometry, let's call it allocate_image_data for now (sounds a bit redundant), then the user could allocate ImageData with proper geometry like this
```
ag = AcquisitionGeometry('parallel','2D', angles, 
                             detectors,
                             pixel_size_h = voxels)

data = ag.allocate_image_data()
```

**Comment by jakobsj** [comment]
This sounds good. As you pointed out, perhaps reconsider the name, to
highlight that it sets a default image geometry, and also I'm not a big fan
of "allocate", especially since we are not really allocating much memory.
No wait, is the suggestion to actually create an ImageData with a default
geometry?  I would have thought to just create a default image geometry,
not data. So I thought maybe "create_default_image_geometry", though
perhaps a bit long, and perhaps it is even more convenient to create the
default image data, which will include the image geometry. Thoughts?

**Comment by evelinaametova** [comment]
Originally I thought to create ImageData with proper geometry. I don't know, maybe it make more sense to create only ImageGeometry. @epapoutsellis , what do you think?

**Comment by epapoutsellis** [comment]
At the moment, after we define an acquisition geometry (parallel case) and pass voxel size of detector, we give the same voxel size for the ImageGeometry. We should force that show the user will not worry. Let's tag as an enhancement for now

**Comment by gfardell** [comment]
`AcquisitionGeometry.get_ImageGeometry()` returns you a default ImageGeometry as of [CCPi-framwork #609](https://github.com/vais-ral/CCPi-Framework/pull/609)
