### ISSUE TITLE
convert_geometry_to_astra

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-astra#46]
`convert_geometry_to_astra` currently [blindly](https://github.com/vais-ral/CCPi-astra/blob/master/Wrappers/Python/ccpi/astra/utils/convert_geometry_to_astra.py#L39) takes the data in the `angles` field of the `AcquisitionGeometry` and passes it to astra. 

Since in `AcquisitionGeometry` we have a field [`angle_unit`](https://github.com/vais-ral/CCPi-Framework/blob/master/Wrappers/Python/ccpi/framework/framework.py#L274) by default set to `DEGREE` we should make use of that. 

Also Astra wants a `numpy.ndarray` of type `numpy.float32`, so that could be rightly and easily created by the `convert_geometry_to_astra` function

**Comment by paskino** [comment]
Additionally I see that at runtime one can end up in [these](https://github.com/vais-ral/CCPi-astra/blob/master/Wrappers/Python/ccpi/astra/utils/convert_geometry_to_astra.py#L43) lines. I believe there should be a 
```python

raise NotImplementedError('error message')
```

**Comment by gfardell** [comment]
I think this is all going to change with the AG redesign so I'm not sure it's worth doing now.
