### ISSUE TITLE
numpy flip

### ISSUE THREAD

**Issue by epapoutsellis** [vais-ral/CCPi-astra#49]
If we build with numpy 1.11 there is no `flip` module in numpy. Flip needs to be replace in `FBP.py` [here](https://github.com/vais-ral/CCPi-astra/blob/190a5a7679c506e9fc78969ec0f1df4f730aa6f7/Wrappers/Python/ccpi/astra/processors/FBP.py#L243)

**Comment by gfardell** [comment]
The minimum version of numpy we support is now numpy 1.15 so this is no longer an issue.
