### ISSUE TITLE
An issue with the conda-build

### ISSUE THREAD

**Issue by dkazanc** [vais-ral/CCPi-astra#8]
I get the following error when I do conda-build:
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['astra-toolbox']

I do conda build conda-recipe --numpy 1.12 --python 3.5 and astra 1.8.3 is installed in environment.

**Comment by jakobsj** [comment]
I believe you need to specify the astra channel like this:
conda build conda-recipe --numpy 1.12 --python 3.5 -c astra-toolbox

Also, I think I ended up using ASTRA 1.8 after not installing 1.8.3 due to dependency issues with CIL or similar.

**Comment by paskino** [comment]
Please give more details.

For what you say I only see 2 pptions:
1. you did not add the `astra-toolbox` channel in the build command
2. you are installing an incompatible version of astra. I also recall 1.8.3 gave troubles. 

Above the message you've pasted, there will be the description of the packages which generate the incompatibility. Paste that one too.

**Comment by dkazanc** [comment]
it installed with Jakob's comment. I re-installed 1.8.3. also after it started complaining...
